[package]
name = "mksettings"
version = "0.1.0"
edition = "2021"
authors = [
    "Björn Quentin <bjoern.quentin@mobile-j.de>",
]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
